// lib/ophthalmology-data.ts
import dbConnect from "@/lib/dbConnect";
import {
  OphthalmologyRecord,
  IOphthalmologyRecord,
} from "@/lib/models/ophthalmology/OphthalmologyRecord";
import { OphthalmologyDailyRecord } from "@/types/ophthalmology";
import mongoose from "mongoose";

// Helper function to convert database model to API type
function toOphthalmologyRecord(
  record: IOphthalmologyRecord
): OphthalmologyDailyRecord {
  return {
    id: record._id.toString(),
    recordNumber: record.recordNumber,
    patientId: record.patientId,
    patientName: record.patientName,
    patientPhone: record.patientPhone,
    recordDate: record.recordDate.toISOString(),
    recordType: record.recordType,
    doctorName: record.doctorName,
    chiefComplaint: record.chiefComplaint,
    examinationFindings: record.examinationFindings,
    diagnosis: record.diagnosis,
    treatment: record.treatment,
    prescriptions: record.prescriptions || [],
    notes: record.notes,
    totalAmount: record.totalAmount,
    paidAmount: record.paidAmount,
    dueAmount: record.dueAmount,
    paymentStatus: record.paymentStatus,
    createdAt: record.createdAt.toISOString(),
    updatedAt: record.updatedAt.toISOString(),
  };
}

// Database operations for Ophthalmology Records
export async function getOphthalmologyRecords(): Promise<
  OphthalmologyDailyRecord[]
> {
  await dbConnect();
  const records = await OphthalmologyRecord.find().sort({ createdAt: -1 });
  return records.map(toOphthalmologyRecord);
}

export async function getOphthalmologyRecordById(
  id: string
): Promise<OphthalmologyDailyRecord | null> {
  await dbConnect();
  const record = await OphthalmologyRecord.findById(id);
  return record ? toOphthalmologyRecord(record) : null;
}

export async function addOphthalmologyRecord(
  data: Partial<OphthalmologyDailyRecord>
): Promise<OphthalmologyDailyRecord> {
  await dbConnect();
  const recordNumber = await (
    OphthalmologyRecord as mongoose.Model<IOphthalmologyRecord> & {
      generateRecordNumber(): Promise<string>;
    }
  ).generateRecordNumber();

  const record = new OphthalmologyRecord({
    recordNumber,
    // patientId is auto-generated by schema if not provided
    patientName: data.patientName,
    patientPhone: data.patientPhone,
    recordDate: data.recordDate || new Date(),
    recordType: data.recordType,
    doctorName: data.doctorName,
    chiefComplaint: data.chiefComplaint,
    examinationFindings: data.examinationFindings,
    diagnosis: data.diagnosis,
    treatment: data.treatment,
    prescriptions: data.prescriptions || [],
    notes: data.notes,
    totalAmount: data.totalAmount || 0,
    paidAmount: data.paidAmount || 0,
    dueAmount: data.dueAmount || 0,
    paymentStatus: data.paymentStatus || "unpaid",
  });

  await record.save();
  return toOphthalmologyRecord(record);
}

export async function updateOphthalmologyRecord(
  id: string,
  updates: Partial<OphthalmologyDailyRecord>
): Promise<OphthalmologyDailyRecord | null> {
  await dbConnect();
  const record = await OphthalmologyRecord.findByIdAndUpdate(
    id,
    { $set: updates },
    { new: true }
  );
  return record ? toOphthalmologyRecord(record) : null;
}

export async function deleteOphthalmologyRecord(id: string): Promise<boolean> {
  await dbConnect();
  const result = await OphthalmologyRecord.findByIdAndDelete(id);
  return !!result;
}

export async function getOphthalmologyRecordsByPatient(
  patientId: string
): Promise<OphthalmologyDailyRecord[]> {
  await dbConnect();
  const records = await OphthalmologyRecord.find({ patientId }).sort({
    recordDate: -1,
  });
  return records.map(toOphthalmologyRecord);
}

export async function getOphthalmologyRecordsByDateRange(
  startDate: Date,
  endDate: Date
): Promise<OphthalmologyDailyRecord[]> {
  await dbConnect();
  const records = await OphthalmologyRecord.find({
    recordDate: {
      $gte: startDate,
      $lte: endDate,
    },
  }).sort({ recordDate: -1 });
  return records.map(toOphthalmologyRecord);
}
